title: Anki cho khá nhiều ngôn ngữ
description: Kho thẻ 1000 từ vựng phổ biến cho các ngôn ngữ như Tiếng Đức, Tiếng Pháp, Tiếng Tây Ban Nha, Tiếng Bồ Đào Nha, Tiếng Nga, Tiếng Ý, Tiếng Thái, Tiếng Ả Rập (Với Tiếng Thái và Tiếng Ả Rập là 500 từ).
show_downloads: false
theme: jekyll-theme-hacker